name: build-qemu-aarch64
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y \
            clang lld llvm qemu-system-arm qemu-system-misc make
      - name: Build
        run: make -j
      - name: Smoke run (5s)
        run: |
          timeout 5s qemu-system-aarch64 -machine virt,gic-version=3 -cpu cortex-a72 \
            -smp 1 -m 512 -nographic -serial mon:stdio \
            -kernel build/kernel.elf || true
      - name: Upload ELF
        uses: actions/upload-artifact@v4
        with:
          name: kernel-elf
          path: build/kernel.elf
